### ISSUE TITLE
Extremely simple example creating and handling a command

### ISSUE THREAD

**Issue by manuelconesa** [simplesoft-pt/Mediator#11]
Hi.

I would really love to implement mediator in my project. I have read your documentation and seems almost complete. 

The only thing remaining would be a very simple piece of code creating a mediator, a command handler and sending a command from Main() .

That would be extremely helpful. 
If you do so, I promise to publish a tutorial using your nuget package.

:)

**Comment by gravity00** [comment]
I'll create an example soon, now that you requested it, probably this week or so.

**Comment by manuelconesa** [comment]
That would be awesome. Honestly, I believe that kind of example is the only piece remaining for this component to be much more widely adopted by many developers. Seems a lightweight alternative to some other mediator frameworks which are literally overkill...

**Comment by gravity00** [comment]
Just created an ASP.NET Core API into the _work_ folder that exemplifies the usage of commands and queries, with logging, validation and EF Core transaction pipeline, I believe it should be enough for what you asked?

https://github.com/simplesoft-pt/Mediator/tree/master/work/SimpleSoft.Mediator.Example.Api

**Comment by manuelconesa** [comment]
OMG!

Thank you so much. It´s not exactly what I would consider an _extremely simple example_. (I was expecting something like a c# project sending messages in command line like "Hello. I am a command sent". "hello. I have validated the command", "hello, I am a message received" and "hi from the pipeline" to start with :))

But I am now playing with its swagger interface.

Thanks for your huge effort!

**Comment by gravity00** [comment]
Ah, for that I already provided a console application: https://github.com/simplesoft-pt/Mediator/tree/master/work
