### ISSUE TITLE
Coming from someone who didn't know anything about this sort of stuff

### ISSUE THREAD

**Issue by MeTitus** [simplesoft-pt/Mediator#7]
it kind of seems like a lost effort, especially when I told you about MediatR, 1 year ago 

https://github.com/jbogard/MediatR

Also learn the concepts properly or you'll make yourself look weird, commands are sent not published and you can't have an handler with both queries and commands that defies the propose of using both in the first place.

**Comment by gravity00** [comment]
@MeTitus thanks for the feedback about the `Send` over `Publish` naming. That was one of the reasons I haven't released the final version yet. I had some doubts in the naming for that exact method.
